version:  "3.8"



services:

  mongo:
    image: mongo:6.0
    container_name: NEG-mongodb
    ports:
      - "27018:27017"
    command: mongod --noauth
    networks:
      - NEG-network
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: NEG_mongo-express
    restart: always
    networks:
      - NEG-network
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_DATABASE: ""
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
      ME_CONFIG_BASICAUTH_USERNAME: "kliuvert"
      ME_CONFIG_BASICAUTH_PASSWORD: "Winner123"
    depends_on:
      - mongo


networks:
  NEG-network:
    driver: bridge


volumes:
  mongo-data: